### ISSUE TITLE
<platform>_app_list cannot return entire list of apps

### ISSUE THREAD

**Issue by lyndsey-ferguson** [AckeeCZ/fastlane-plugin-firebase_management#2]
The way that the `ios_app_list` and `android_app_list` work cannot return the entire list of apps because the API can return a subset of the apps.

To fix this, the `nextPageToken` should be reviewed and the API should be called again with that token.

**Comment by tmaly1980** [comment]
https://github.com/AckeeCZ/fastlane-plugin-firebase_management/pull/3

Hopefully this can be merged soon. Until then I'm going to have gem read from https://github.com/tmaly1980/fastlane-plugin-firebase_management/tree/patch-1

**Comment by janmisar** [comment]
Resolved in #3. Thanks you guys 👍

**Comment by carlosefonseca** [comment]
Please release version 1.0.2 with the fix. Thanks!

**Comment by janmisar** [comment]
> Please release version 1.0.2 with the fix. Thanks!

✅
