### ISSUE TITLE
You must define service_account_json_path or email with client_secret_json_path

### ISSUE THREAD

**Issue by ssathishppm** [AckeeCZ/fastlane-plugin-firebase_management#4]
when executing this command - bundle exec fastlane test_list
+------------------------+---------+------------------------+
|                       Used plugins                        |
+------------------------+---------+------------------------+
| Plugin                 | Version | Action                 |
+------------------------+---------+------------------------+
| fastlane-plugin-fireb  | 1.1.0   | firebase_add_app       |
| ase_management         |         | firebase_download_con  |
|                        |         | fig firebase_list      |
+------------------------+---------+------------------------+

undefined method `service_account_json_path' for #<CredentialsManager::AppfileConfig:0x007fb3ef1a0c20>
undefined method `service_account_json_path' for #<CredentialsManager::AppfileConfig:0x007fb3ef1d2568>
[18:27:43]: Driving the lane 'test_list' 🚀
[18:27:43]: --------------------------------------
[18:27:43]: --- Step: firebase_management_list ---
[18:27:43]: --------------------------------------
[18:27:43]: You must define service_account_json_path or email with client_secret_json_path.

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | firebase_management_l  | 0           |
|      | ist                    |             |
+------+------------------------+-------------+

[18:27:43]: fastlane.tools finished successfully 🎉

Where i have to add this service_account_json_path ?

**Comment by ssathishppm** [comment]
Waiting for the reply. 
I have below files in my fastlane folder react native
Appfile
Fastfile
Gymfile
Pluginfile

**Comment by janmisar** [comment]
I don't understand why you're trying to use our test lane 🤔
Anyway... regarding your question..

Run `fastlane action firebase_management_list`.
`service_account_json_path` is just standard action parameter, so pass it where you're calling list action or set environment variable.

**Comment by ssathishppm** [comment]
Thanks @janmisar set the service account json path in environment variable. 
ENV["FIREBASE_SERVICE_ACCOUNT_JSON_PATH"] = "Json file full path". it's working now.
